### PR TITLE
added function test_set_quantity_from_file to test the results of set_quantity and set_values from pts, asc and dem files

### PR DESCRIPTION
**Pull request by acer8**
added function test_set_quantity_from_file in test_shallow_water_domain.py to test the results of set_quantity and set_values from pts, asc and dem files. The result of set_quantity and set_values should be the same.

### CODE REVIEW

**Comment by acer8** [comment]
Looks like there's a bug in the new anuga/utilities/plot_utils.py". Because at line 859, in get_triangle_lookup_function, 'Triangulation' object has no attribute 'get_trifinder'. Python 2.7.6 (my machine) has get_trifinder method but probably Python 2.7.3 (which is the one built in Travis CI) doesn't.

**Comment by stoiver** [comment]
I'm going to close and then open this PR so as to initiate a new build test.

**Comment by stoiver** [comment]
Reopen PR to test build

**Comment by stoiver** [comment]
So we are still getting the matplotlib error. I have just merged a fix forthat problem. So lets see if I can get travis tosuccessfully build now. So I will closeand open this PR again.

**Comment by stoiver** [comment]
Reopen PR to forceTravis to do its build test

**Comment by acer8** [comment]
Thanks Steve!

**Pull request merged**
