### PR TITLE
Updated to latest pymetis.

### PR DESCRIPTION
**Pull request by ninnghazad**
Updated to latest pymetis, which uses metis 5. Including our own version of pymetis with anuga should not be necessary anymore. Installers are not yet updated to reflect that. And pymetis has not yet been removed from the tree.

### CODE REVIEW

**Comment by ninnghazad** [comment]
See #15

**Comment by stoiver** [comment]
@ninnghazad  I don't have a mac so can't easily check the best way to install pymetis. But pretty sure you need to install with pip AFTER miniconda is installed and activated. It is possible that the mac clang compiler has trouble with the installation of pymetis. 

Just noticed that the windows CI tests are actually failing too. I'll have to investigate why appVeyor doesn't pick up the error. So we will have to add a pip install pymetis to appveyor.yml as well.

Maybe we will need to compile with mingw. It is a little hard to get pip to use mingw, so actually it might be easier to download pymetis from github and install from source using 
```
python setup.py build --compiler=mingw32 
```
just like we do for anuga. 

And finally once we get your additions passing the tests, we will have to put back the old pymetis based on metis4 as a fall back if pymetis is not installed, then they still have a working code. This will be easy, as we just put a `try: import pymetis` and deal  with the cases.

**Comment by adamjstewart** [comment]
I would also be interested in this. See #247 for the problem with the current version. Ideally, there wouldn't be any vendored dependencies and I could use external installations of all of them, but I haven't yet figured out how to do that.

**Comment by stoiver** [comment]
We have merged this into our python 3 version of the code (available from  anuga-community/anuga_core ). I will close this now.

**Pull request closed without merging**
